services:
  mongodb:
    image: bitnami/mongodb:latest
    volumes:
      - mongodb_data:/bitnami/mongodb
    ports:
      - "27017:27017"
    expose:
      - "27017"
    restart: on-failure

  api:
    image: 34.9.130.218:5000/dev/uss-api:latest
    ports:
      - "8000:8000"
    expose:
      - "8000"
    environment:
      ENV: "prod"
    depends_on:
      - mongodb
    
  interface:
    image: 34.9.130.218:5000/dev/uss-viewer:latest
    ports:
      - "80:80"
    expose:
      - "80"
    depends_on:
      - api
  
volumes:
  mongodb_data:
