services:
  api:
    image: 35.224.119.143:5000/dev/uss-api:latest
    ports:
      - "8000:8000"
    expose:
      - "8000"
    environment:
      ENV: "prod"
    restart: on-failure
    deploy:
      replicas: 1
    
  interface:
    image: 35.224.119.143:5000/dev/uss-viewer:latest
    ports:
      - "80:80"
    expose:
      - "80"
    depends_on:
      - api
    restart: on-failure
    deploy:
      replicas: 1
  
volumes:
  data:
