version: "3.8"

services:
  api:
    build: ./backend
    ports:
      - "8001:8000"
    environment:
      - ENV=prod
    depends_on:
      - mongodb

  mongodb:
    image: bitnami/mongodb:latest
    ports:
      - "27018:27017"
    volumes:
      - data:/bitnami/mongodb

volumes:
  data:
