services:
  mongodb:
    image: bitnami/mongodb:latest
    environment:
      - MONGODB_ROOT_PASSWORD=your-secure-password
    volumes:
      - mongodb_data:/bitnami/mongodb
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure 

  dss-migration-rid:
    image: 172.18.31.16:5000/dev/dss-core-service:latest
    restart: on-failure
    logging:
      driver: fluentd
      options:
        tag: dss-rid-migration
    command: /usr/bin/db-manager migrate --schemas_dir=/db-schemas/rid --db_version "latest" --cockroach_host ${COCKROACH_HOST} --cockroach_port ${COCKROACH_PORT}
    networks:
      - dss_db
  
  dss-migration-scd:
    image: 172.18.31.16:5000/dev/dss-core-service:latest
    restart: on-failure
    logging:
      driver: fluentd
      options:
        tag: dss-scd-migration
    command: /usr/bin/db-manager migrate --schemas_dir=/db-schemas/scd --db_version "latest" --cockroach_host ${COCKROACH_HOST} --cockroach_port ${COCKROACH_PORT}
    networks:
      - dss_db
    

networks:
  app-network:
    external: true
