version: "3.8"

services:
  api:
    image: your-username/your-app-backend:latest
    ports:
      - "8001:8000"
    environment:
      - ENV=prod
      - MONGODB_URL=mongodb://mongodb:27017
    depends_on:
      - mongodb
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  frontend:
    image: your-username/your-app-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  mongodb:
    image: bitnami/mongodb:latest
    environment:
      - MONGODB_ROOT_PASSWORD=your-secure-password
    volumes:
      - mongodb_data:/bitnami/mongodb
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

networks:
  app-network:
    driver: overlay

volumes:
  mongodb_data:
    driver: local
